#! /bin/bash

# This is an ungodly ugly script to change all the package statement
# to the current folder name. Kids don't do this at home.

ls *.java | xargs sed -ri'' "s/package blahbot;/package team070;/"
